apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registrylzn7863.azurecr.io/poi:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: poi
          value: "poi"
        - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
        - name: SQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: eB8hv3Ke5
        - name: SQL_USER
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: sqladminlZn7863
        - name: SQL_SERVER
        valueFrom:
          secretKeyRef:
            name: mysqlserver
            key: sqlserverlzn7863.database.windows.net
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: poi
