apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web-dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registrylzn7863.azurecr.io/tripviewer:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: tripviewer
          value: "tripviewer"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips:80"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web-dev  
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer
