kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-api-user-full-access
  namespace: api-dev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]